version: '3'
services:
  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_USER=your_user_name
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db_name
      - POSTGRES_HOST=db
      - JWT_SECRET_KEY=your-secret-key
      - SECRET_KEY=your-secret-key
      - SQLALCHEMY_DATABASE_URI=postgresql://username:password@db:5432/db_name
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_user_name
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=db_name
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: